server:
  port: 10001

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:mem:account
    username: admin
    password: admin
  h2:
    console:
      enabled: true
axon:
  axonserver:
    servers: localhost:8124
